### PR TITLE
Add alias example

### PR DESCRIPTION
**Pull request by jyucsiro**
This addresses #44

### CODE REVIEW

**Comment by jyucsiro** [comment]
Also #43, although I think #44 and #43 talk are about the same thing now that i have revisited them both

**Comment by marqh** [comment]
i wonder if it would help to have a side by side comparison of plain JSON and JSON-LD in this PR

I thInk we should only have one, but I wonder how different the JSON-LD would look

**Comment by jyucsiro** [comment]
So the JSON-LD would look like this:
```
{
  "@context": {
    "dct": "http://purl.org/dc/terms/",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "acdd": "https://def.scitools.org.uk/ACDD/",
    "cfterms": "https://def.scitools.org.uk/CFTerms/",
    "nc": "https://def.scitools.org.uk/NetCDF/",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "op": "http://environment.data.gov.au/def/op#"
  },
  "@graph": [
    {
      "@id": "skos:prefLabel",
      "dct:identifier": "prefLabel"
    },
    {
      "@id": "acdd:id",
      "dct:identifier": "id"
    },
    {
      "@id": "acdd:title",
      "dct:identifier": "title"
    },
    {
      "@id": "cfterms:standard_name",
      "dct:identifier": "standard_name"
    },
    {
      "@id": "cfterms:units",
      "dct:identifier": "units"
    },
    {
      "@id": "op:matrix",
      "dct:identifier": "matrix"
    },
    {
      "@id": "op:objectOfInterest",
      "dct:identifier": "substanceOrTaxon"
    },
    {
      "@id": "nc:valid_max",
      "dct:identifier": "valid_max"
    },
    {
      "@id": "nc:valid_min",
      "dct:identifier": "valid_min"
    }
  ]
}
```
A point in our discussion was that while this is JSON, it is more of an alternative to the Turtle encoding rather than the plain JSON list alternative.

**Comment by adamml** [comment]
The following JSON Schema should constrain the "plain" JSON used in the alias example. If we think the _value_ should always begin http[s]:// then I can look at editing the JSON Schema to accommodate that constraint too.

```yaml
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "netcdf-ld__alias",
    "type": "object",
    "patternProperties": {
        "^.*$": {
            "anyOf": [{
                "type": "string"
            }]
        }
    }
}
```

**Comment by jyucsiro** [comment]
Thanks @adamml  - the JSON schema looks good. Do we add the JSON Schema definition in Section 6?

**Comment by jyucsiro** [comment]
At the telecon today, we discussed options for publishing the JSON Schema as a resource available for validation and other uses. Perhaps alongside the current tests.

Need to adapt the current requirements in Section 7.3 to allow specification aliases via plain JSON - see #72

**Comment by jyucsiro** [comment]
@marqh are you happy for us to merge this PR? I've created issue #72 to work on including the JSON schema in tests and text in the spec around plain json encoding requirements for aliases. if we merge this, then i can create another PR for issue 72. ta

**Pull request merged**
